export const NCERT_HOST = 'https://ncert.nic.in/textbook/pdf';
export const SOLUTIONS_HOST = 'https://ipfs.filebase.io/ipfs';

export const BOOKS = 'books';
export const SOLUTIONS = 'solutions';

export const BOOKS_ARRAY = [
  {
    class: 1,
    subjects: ['english', 'mathematics', 'hindi', 'urdu'],
    english: ['marigold', 'raindrops'],
    marigold: [...Array(10).keys()],
    marigold_pdf_key: 'aeen1',
    raindrops: [...Array(19).keys()],
    raindrops_pdf_key: 'aerd1',
    mathematics: [
      'math_magic',
      'ganit_ka_jaadu_hindi',
      'riyazi_ka_jadoo_I_urdu',
    ],
    math_magic: [...Array(13).keys()],
    math_magic_pdf_key: 'aemh1',
    ganit_ka_jaadu_hindi: [...Array(13).keys()],
    ganit_ka_jaadu_hindi_pdf_key: 'ahmh1',
    riyazi_ka_jadoo_I_urdu: [...Array(13).keys()],
    riyazi_ka_jadoo_I_urdu_pdf_key: 'auri1',
    hindi: ['rimjhim'],
    rimjhim_pdf_key: 'ahhn1',
    rimjhim: [...Array(19).keys()],
    urdu: ['ibtedai_urdu_i'],
    ibtedai_urdu_i_pdf_key: 'aulb1',
    ibtedai_urdu_i: [...Array(19).keys()],
  },
  {
    class: 2,
    subjects: ['english', 'mathematics', 'hindi', 'urdu'],
    english: ['marigold', 'raindrops'],
    marigold: [...Array(10).keys()],
    marigold_pdf_key: 'been1',
    raindrops: [...Array(15).keys()],
    raindrops_pdf_key: 'berd1',
    mathematics: [
      'math_magic',
      'ganit_ka_jaadu_hindi',
      'riyazi_ka_jadu_II_urdu',
    ],
    math_magic: [...Array(15).keys()],
    math_magic_pdf_key: 'bemh1',
    ganit_ka_jaadu_hindi: [...Array(15).keys()],
    ganit_ka_jaadu_hindi_pdf_key: 'bhmh1',
    riyazi_ka_jadu_II_urdu: [...Array(15).keys()],
    riyazi_ka_jadu_II_urdu_pdf_key: 'buri1',
    hindi: ['rimjhim'],
    rimjhim_pdf_key: 'bhhn1',
    rimjhim: [...Array(15).keys()],
    urdu: ['ibtedai_urdu_II'],
    ibtedai_urdu_II: [...Array(20).keys()],
    ibtedai_urdu_II_pdf_key: 'buib1',
  },
  {
    class: 3,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'environmental_studies',
      'urdu',
    ],
    hindi: ['rimjhim'],
    rimjhim: [...Array(13).keys()],
    rimjhim_pdf_key: 'chhn1',
    english: ['marigold'],
    marigold: [...Array(10).keys()],
    marigold_pdf_key: 'ceen1',
    mathematics: ['maths', 'ganit_hindi', 'riyazi_ka_jadu_III_urdu'],
    maths: [...Array(14).keys()],
    maths_pdf_key: 'cemh1',
    ganit_hindi: [...Array(14).keys()],
    ganit_hindi_pdf_key: 'chmh1',
    riyazi_ka_jadu_III_urdu: [...Array(14).keys()],
    riyazi_ka_jadu_III_urdu_pdf_key: 'curi1',
    environmental_studies: [
      'looking_around',
      'ass_pass_hindi',
      'ass_pass_urdu',
    ],
    looking_around: [...Array(24).keys()],
    looking_around_pdf_key: 'ceap1',
    ass_pass_hindi: [...Array(24).keys()],
    ass_pass_hindi_pdf_key: 'chap1',
    ass_pass_urdu: [...Array(24).keys()],
    ass_pass_urdu_pdf_key: 'cuap1',
    urdu: ['ibtedai_urdu'],
    ibtedai_urdu: [...Array(20).keys()],
    ibtedai_urdu_pdf_key: 'culb1',
  },
  {
    class: 4,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'environmental_studies',
      'urdu',
    ],
    hindi: ['rimjhim'],
    rimjhim: [...Array(14).keys()],
    rimjhim_pdf_key: 'dhhn1',
    english: ['marigold'],
    marigold: [...Array(9).keys()],
    marigold_pdf_key: 'deen1',
    mathematics: [
      'math_magic',
      'ganit_ka_jadu_hindi',
      'riyazi_ka_jadu_IV_urdu',
    ],
    math_magic: [...Array(14).keys()],
    math_magic_pdf_key: 'demh1',
    ganit_ka_jadu_hindi: [...Array(14).keys()],
    ganit_ka_jadu_hindi_pdf_key: 'dhmh1',
    riyazi_ka_jadu_IV_urdu: [...Array(14).keys()],
    riyazi_ka_jadu_IV_urdu_pdf_key: 'duri1',
    environmental_studies: [
      'looking_around',
      'ass_pass_hindi',
      'ass_pass_urdu',
    ],
    looking_around: [...Array(27).keys()],
    looking_around_pdf_key: 'deap1',
    ass_pass_hindi: [...Array(27).keys()],
    ass_pass_hindi_pdf_key: 'dhap1',
    ass_pass_urdu: [...Array(27).keys()],
    ass_pass_urdu_pdf_key: 'duap1',
    urdu: ['ibtedai_urdu_IV'],
    ibtedai_urdu_IV: [...Array(22).keys()],
    ibtedai_urdu_IV_pdf_key: 'dulb1',
  },
  {
    class: 5,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'environmental_studies',
      'urdu',
    ],
    hindi: ['rimjhim'],
    rimjhim: [...Array(18).keys()],
    rimjhim_pdf_key: 'ehhn1',
    english: ['marigold'],
    marigold: [...Array(10).keys()],
    marigold_pdf_key: 'eeen1',
    mathematics: ['math_magic', 'ganit_ka_jadu_hindi', 'riyazi_ka_jadu_V_urdu'],
    math_magic: [...Array(14).keys()],
    math_magic_pdf_key: 'eemh1',
    ganit_ka_jadu_hindi: [...Array(14).keys()],
    ganit_ka_jadu_hindi_pdf_key: 'ehmh1',
    riyazi_ka_jadu_V_urdu: [...Array(14).keys()],
    riyazi_ka_jadu_V_urdu_pdf_key: 'euri1',
    environmental_studies: ['looking around', 'ass_pass', 'ass_pass_urdu'],
    looking_around: [...Array(22).keys()],
    looking_around_pdf_key: 'eeap1',
    ass_pass: [...Array(22).keys()],
    ass_pass_pdf_key: 'ehap1',
    ass_pass_urdu: [...Array(22).keys()],
    ass_pass_urdu_pdf_key: 'euap1',
    urdu: ['ibtedai_urdu_V'],
    ibtedai_urdu_V: [...Array(22).keys()],
    ibtedai_urdu_V_pdf_key: 'eulb1',
  },
  {
    class: 6,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'social_science',
      'sanskrit',
      'science',
      'urdu',
    ],
    hindi: ['vasant', 'durva', 'bal_ram_katha'],
    vasant: [...Array(14).keys()],
    vasant_pdf_key: 'fhvs1',
    durva: [...Array(28).keys()],
    durva_pdf_key: 'fhdv1',
    bal_ram_katha: [...Array(12).keys()],
    bal_ram_katha_pdf_key: 'fhbr1',
    english: ['honeysuckle', 'a_pact_with_the_sun'],
    honeysuckle: [...Array(8).keys()],
    honeysuckle_pdf_key: 'fehl1',
    a_pact_with_the_sun: [...Array(7).keys()],
    a_pact_with_the_sun_pdf_key: 'fepw1',
    mathematics: ['maths', 'ganit_hindi', 'riyazi_urdu'],
    maths: [...Array(12).keys()],
    maths_pdf_key: 'femh1',
    ganit_hindi: [...Array(12).keys()],
    ganit_hindi_pdf_key: 'fhmh1',
    riyazi_urdu: [...Array(12).keys()],
    riyazi_urdu_pdf_key: 'furi1',
    social_science: [
      'history_our_past',
      'the_earth_our_habitat',
      'hamare_ateet_hindi',
      'social_and_political_life',
      'samajik_evem_rajnitik_jeevan_hindi',
      'prithavi_hamara_avas_hindi',
      'hamare_mazi_urdu',
      'zameen_hamara_maskan_urdu',
      'samazi_aur_siyasi_zindagi_urdu',
    ],
    history_our_past: [...Array(10).keys()],
    history_our_past_pdf_key: 'fess1',
    the_earth_our_habitat: [...Array(6).keys()],
    the_earth_our_habitat_pdf_key: 'fess2',
    hamare_ateet_hindi: [...Array(10).keys()],
    hamare_ateet_hindi_pdf_key: 'fhss1',
    social_and_political_life: [...Array(8).keys()],
    social_and_political_life_pdf_key: 'fess3',
    samajik_evem_rajnitik_jeevan_hindi: [...Array(8).keys()],
    samajik_evem_rajnitik_jeevan_hindi_pdf_key: 'fhss3',
    prithavi_hamara_avas_hindi: [...Array(6).keys()],
    prithavi_hamara_avas_hindi_pdf_key: 'fhss2',
    hamare_mazi_urdu: [...Array(11).keys()],
    hamare_mazi_urdu_pdf_key: 'fuhm1',
    zameen_hamara_maskan_urdu: [...Array(8).keys()],
    zameen_hamara_maskan_urdu_pdf_key: 'fuzm1',
    samazi_aur_siyasi_zindagi_urdu: [...Array(9).keys()],
    samazi_aur_siyasi_zindagi_urdu_pdf_key: 'fuss1',
    sanskrit: ['ruchira'],
    ruchira: [...Array(13).keys()],
    ruchira_pdf_key: 'fhsk1',
    science: ['vigyan_hindi', 'science_VI', 'science_urdu'],
    vigyan_hindi: [...Array(11).keys()],
    vigyan_hindi_pdf_key: 'fhsc1',
    science_VI: [...Array(11).keys()],
    science_VI_pdf_key: 'fesc1',
    science_urdu: [...Array(16).keys()],
    science_urdu_pdf_key: 'fuse1',
    urdu: ['apni_zuban_VI', 'urdu_guldasta', 'jaan_pahechan'],
    jaan_pahechan: [...Array(32).keys()],
    jaan_pahechan_pdf_key: 'fujp1',
    apni_zuban_VI: [...Array(20).keys()],
    apni_zuban_VI_pdf_key: 'fuaz1',
    urdu_guldasta: [...Array(11).keys()],
    urdu_guldasta_pdf_key: 'fuug1',
  },
  {
    class: 7,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'social_science',
      'sanskrit',
      'science',
      'urdu',
    ],
    hindi: ['vasant', 'durva', 'mahabharat'],
    vasant: [...Array(15).keys()],
    vasant_pdf_key: 'ghvs1',
    durva: [...Array(18).keys()],
    durva_pdf_key: 'ghdv1',
    mahabharat: [...Array(1).keys()],
    mahabharat_pdf_key: 'ghmb1',
    english: ['honeycomb', 'an_alien_hand_supplementry_reader'],
    honeycomb: [...Array(8).keys()],
    honeycomb_pdf_key: 'gehc1',
    an_alien_hand_supplementry_reader: [...Array(7).keys()],
    an_alien_hand_supplementry_reader_pdf_key: 'geah1',
    mathematics: ['maths', 'ganit_hindi', 'hisaab_urdu'],
    maths: [...Array(13).keys()],
    maths_pdf_key: 'gemh1',
    ganit_hindi: [...Array(13).keys()],
    ganit_hindi_pdf_key: 'ghmh1',
    hisaab_urdu: [...Array(15).keys()],
    hisaab_urdu_pdf_key: 'guma1',
    social_science: [
      'social_and_political_life',
      'samajik_evem_rajniti_jeevan_hindi',
      'samazi_aur_siyasi_zindagi_urdu',
      'our_past_II',
      'hamare_ateet_II_hindi',
      'our_environment',
      'hamara_paryavaran_hindi',
      'hamare_mazi_urdu',
      'hamare_mahol_urdu',
    ],
    social_and_political_life: [...Array(8).keys()],
    social_and_political_life_pdf_key: 'gess3',
    samajik_evem_rajniti_jeevan_hindi: [...Array(8).keys()],
    samajik_evem_rajniti_jeevan_hindi_pdf_key: 'ghss3',
    samazi_aur_siyasi_zindagi_urdu: [...Array(9).keys()],
    samazi_aur_siyasi_zindagi_urdu_pdf_key: 'guss3',
    our_past_II: [...Array(8).keys()],
    our_past_II_pdf_key: 'gess1',
    our_environment: [...Array(7).keys()],
    our_environment_pdf_key: 'gess2',
    hamare_ateet_II_hindi: [...Array(8).keys()],
    hamare_ateet_II_hindi_pdf_key: 'ghss1',
    hamara_paryavaran_hindi: [...Array(7).keys()],
    hamara_paryavaran_hindi_pdf_key: 'ghss2',
    hamare_mazi_urdu: [...Array(10).keys()],
    hamare_mazi_urdu_pdf_key: 'guhm1',
    hamare_mahol_urdu: [...Array(9).keys()],
    hamare_mahol_urdu_pdf_key: 'guha1',
    sanskrit: ['ruchira'],
    ruchira: [...Array(13).keys()],
    ruchira_pdf_key: 'ghsk1',
    science: ['vigyan_hindi', 'science_VII', 'science_urdu'],
    vigyan_hindi: [...Array(13).keys()],
    vigyan_hindi_pdf_key: 'ghsc1',
    science_VII: [...Array(13).keys()],
    science_VII_pdf_key: 'gesc1',
    science_urdu: [...Array(18).keys()],
    science_urdu_pdf_key: 'guse1',
    urdu: ['apni_zuban_VII', 'urdu_guldasta', 'door_pass', 'jaan_pahechan'],
    jaan_pahechan: [...Array(20).keys()],
    jaan_pahechan_pdf_key: 'gujp1',
    apni_zuban_VII: [...Array(21).keys()],
    apni_zuban_VII_pdf_key: 'guaz1',
    door_pass: [...Array(26).keys()],
    door_pass_pdf_key: 'gudp1',
    urdu_guldasta: [...Array(15).keys()],
    urdu_guldasta_pdf_key: 'gugu1',
  },
  {
    class: 8,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'social_science',
      'sanskrit',
      'science',
      'urdu',
    ],
    hindi: ['vasant', 'durva', 'bharat_ki_khoj', 'sanshipt_budhcharit'],
    sanshipt_budhcharit: [...Array(5).keys()],
    sanshipt_budhcharit_pdf_key: 'hhsb1',
    vasant: [...Array(13).keys()],
    vasant_pdf_key: 'hhvs1',
    durva: [...Array(19).keys()],
    durva_pdf_key: 'hhdv1',
    bharat_ki_khoj: [...Array(9).keys()],
    bharat_ki_khoj_pdf_key: 'hhbk1',
    english: ['honeydew', 'it_so_happend'],
    honeydew: [...Array(8).keys()],
    honeydew_pdf_key: 'gehc1',
    it_so_happend: [...Array(7).keys()],
    it_so_happend_pdf_key: 'geah1',
    mathematics: ['maths', 'ganit_hindi', 'riyazi_urdu'],
    maths: [...Array(13).keys()],
    maths_pdf_key: 'hemh1',
    ganit_hindi: [...Array(13).keys()],
    ganit_hindi_pdf_key: 'hhmh1',
    hisaab_urdu: [...Array(16).keys()],
    hisaab_urdu_pdf_key: 'huhi1',
    social_science: [
      'social_and_political_life',
      'samajik_evem_rajniti_jeevan_hindi',
      'samazi_aur_siyasi_zindagi_urdu',
      'our_past_III',
      'hamare_ateet_III_hindi',
      'resource_and_development',
      'sansadhan_avam_vikas_hindi',
      'hamare_maazi_urdu',
      'wasayel_aur_taraqqui_urdu',
    ],
    social_and_political_life: [...Array(8).keys()],
    social_and_political_life_pdf_key: 'hess3',
    samajik_evem_rajniti_jeevan_hindi: [...Array(8).keys()],
    samajik_evem_rajniti_jeevan_hindi_pdf_key: 'hhss3',
    samazi_aur_siyasi_zindagi_urdu: [...Array(10).keys()],
    samazi_aur_siyasi_zindagi_urdu_pdf_key: 'huss3',
    our_past_III: [...Array(8).keys()],
    our_past_III_pdf_key: 'hess1',
    resource_and_development: [...Array(5).keys()],
    resource_and_development_pdf_key: 'hess4',
    hamare_ateet_III_hindi: [...Array(8).keys()],
    hamare_ateet_III_hindi_pdf_key: 'hhss1',
    sansadhan_avam_vikas_hindi: [...Array(5).keys()],
    sansadhan_avam_vikas_hindi_pdf_key: 'hhss2',
    hamare_maazi_urdu: [...Array(10).keys()],
    hamare_maazi_urdu_pdf_key: 'huhm1',
    wasayel_aur_taraqqui_urdu: [...Array(6).keys()],
    wasayel_aur_taraqqui_urdu_pdf_key: 'hugy1',
    sanskrit: ['ruchira'],
    ruchira: [...Array(14).keys()],
    ruchira_pdf_key: 'hhsk1',
    science: ['vigyan_hindi', 'science_VIII', 'science_urdu'],
    vigyan_hindi: [...Array(13).keys()],
    vigyan_hindi_pdf_key: 'hhsc1',
    science_VIII: [...Array(13).keys()],
    science_VIII_pdf_key: 'hesc1',
    science_urdu: [...Array(18).keys()],
    science_urdu_pdf_key: 'huse1',
    urdu: ['apni_zuban_VIII', 'urdu_guldasta', 'door_pass', 'jaan_pahechan'],
    jaan_pahechan: [...Array(20).keys()],
    jaan_pahechan_pdf_key: 'hujp1',
    apni_zuban_VIII: [...Array(22).keys()],
    apni_zuban_VIII_pdf_key: 'huaz1',
    door_pass: [...Array(20).keys()],
    door_pass_pdf_key: 'hudp1',
    urdu_guldasta: [...Array(9).keys()],
    urdu_guldasta_pdf_key: 'huug1',
  },
  {
    class: 9,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'social_science',
      'sanskrit',
      'science',
      'urdu',
      'health_and_physical_education',
      'ICT',
    ],
    hindi: ['kshitji', 'sprash', 'kritika', 'sanchayan'],
    kshitji: [...Array(13).keys()],
    kshitji_pdf_key: 'ihks1',
    sprash: [...Array(10).keys()],
    sprash_pdf_key: 'ihsp1',
    kritika: [...Array(3).keys()],
    kritika_pdf_key: 'ihkr1',
    sanchayan: [...Array(4).keys()],
    sanchayan_pdf_key: 'ihsa1',
    english: [
      'beehive',
      'moments_supplementary_reader',
      'words_and_expressions_1',
    ],
    beehive: [...Array(9).keys()],
    beehive_pdf_key: 'iebe1',
    moments_supplementary_reader: [...Array(9).keys()],
    moments_supplementary_reader_pdf_key: 'iemo1',
    words_and_expressions_1: [...Array(9).keys()],
    words_and_expressions_1_pdf_key: 'iewe1',
    mathematics: ['maths', 'ganit_hindi', 'riyazi_urdu'],
    maths: [...Array(12).keys()],
    maths_pdf_key: 'iemh1',
    ganit_hindi: [...Array(12).keys()],
    ganit_hindi_pdf_key: 'ihmh1',
    riyazi_urdu: [...Array(15).keys()],
    riyazi_urdu_pdf_key: 'iumh1',
    social_science: [
      'democratic_politics',
      'loktantrik_rajniti_hindi',
      'contemporary_india',
      'samkalin_bharat_hindi',
      'arthashastra_hindi',
      'economics',
      'india_and_contemporary_world_I',
      'bharat_aur_samkalin_vishwa_I_hindi',
      'jamhuri_syasat_urdu',
      'hindustan_aur_asri_dunia_I_urdu',
      'aasri_hindustan_urdu',
      'mashiyat_urdu',
    ],
    democratic_politics: [...Array(5).keys()],
    democratic_politics_pdf_key: 'iess4',
    loktantrik_rajniti_hindi: [...Array(5).keys()],
    loktantrik_rajniti_hindi_pdf_key: 'ihss4',
    contemporary_india: [...Array(6).keys()],
    contemporary_india_pdf_key: 'iess1',
    samkalin_bharat_hindi: [...Array(6).keys()],
    samkalin_bharat_hindi_pdf_key: 'ihss1',
    economics: [...Array(4).keys()],
    economics_pdf_key: 'iess4',
    arthashastra_hindi: [...Array(4).keys()],
    arthashastra_hindi_pdf_key: 'ihss2',
    india_and_contemporary_world_I: [...Array(5).keys()],
    india_and_contemporary_world_I_pdf_key: 'iess3',
    bharat_aur_samkalin_vishwa_I_hindi: [...Array(5).keys()],
    bharat_aur_samkalin_vishwa_I_hindi_pdf_key: 'ihss3',
    jamhuri_syasat_urdu: [...Array(6).keys()],
    jamhuri_syasat_urdu_pdf_key: 'iuss4',
    hindustan_aur_asri_dunia_I_urdu: [...Array(5).keys()],
    hindustan_aur_asri_dunia_I_urdu_pdf_key: 'iuhi1',
    aasri_hindustan_urdu: [...Array(6).keys()],
    aasri_hindustan_urdu_pdf_key: 'iuss1',
    mashiyat_urdu: [...Array(4).keys()],
    mashiyat_urdu_pdf_key: 'iuss2',
    sanskrit: ['shemushi_prathmo', 'vyakaranavithi', 'abhyaswaan_bhav'],
    shemushi_prathmo: [...Array(10).keys()],
    shemushi_prathmo_pdf_key: 'ihsh1',
    vyakaranavithi: [...Array(14).keys()],
    vyakaranavithi_pdf_key: 'jhva1',
    abhyaswaan_bhav: [...Array(12).keys()],
    abhyaswaan_bhav_pdf_key: 'isab1',
    science: ['vigyan_hindi', 'science_IX', 'science_urdu'],
    vigyan_hindi: [...Array(12).keys()],
    vigyan_hindi_pdf_key: 'ihsc1',
    science_IX: [...Array(12).keys()],
    science_IX_pdf_key: 'iesc1',
    science_urdu: [...Array(15).keys()],
    science_urdu_pdf_key: 'iusc1',
    urdu: [
      'gulzare_e_urdu',
      'nawa_e_urdu',
      'door_pass',
      'jaan_pahechan',
      'sab_rang',
      'urdu_ki_adabi_asnaf',
    ],
    jaan_pahechan: [...Array(22).keys()],
    jaan_pahechan_pdf_key: 'iujp1',
    gulzare_e_urdu: [...Array(19).keys()],
    gulzare_e_urdu_pdf_key: 'iugu1',
    door_pass: [...Array(20).keys()],
    door_pass_pdf_key: 'iudp1',
    nawa_e_urdu: [...Array(23).keys()],
    nawa_e_urdu_pdf_key: 'iuna1',
    sab_rang: [...Array(10).keys()],
    sab_rang_pdf_key: 'iusr1',
    urdu_ki_adabi_asnaf: [...Array(40).keys()],
    urdu_ki_adabi_asnaf_pdf_key: 'iuau1',
    health_and_physical_education: ['health_and_physical_education_IX'],
    health_and_physical_education_IX: [...Array(14).keys()],
    health_and_physical_education_IX_pdf_key: 'iehp1',
    ICT: ['information_and_communication_tech'],
    information_and_communication_tech: [...Array(8).keys()],
    information_and_communication_tech_pdf_key: 'iict1',
  },
  {
    class: 10,
    subjects: [
      'hindi',
      'english',
      'mathematics',
      'social_science',
      'sanskrit',
      'science',
      'urdu',
      'health_and_physical_education',
    ],
    hindi: ['kshitji_2', 'sprash', 'kritika', 'sanchayan_2'],
    kshitji_2: [...Array(12).keys()],
    kshitji_2_pdf_key: 'jhks1',
    sprash: [...Array(10).keys()],
    sprash_pdf_key: 'jhsp1',
    kritika: [...Array(3).keys()],
    kritika_pdf_key: 'jhkr1',
    sanchayan_2: [...Array(3).keys()],
    sanchayan_2_pdf_key: 'jhsy1',
    english: [
      'first_flight',
      'footprints_without_feet',
      'words_and_expressions_2',
    ],
    first_flight: [...Array(9).keys()],
    first_flight_pdf_key: 'jeff1',
    footprints_without_feet: [...Array(9).keys()],
    footprints_without_feet_pdf_key: 'jefp1',
    words_and_expressions_2: [...Array(9).keys()],
    words_and_expressions_2_pdf_key: 'jewe2',
    mathematics: ['maths', 'ganit', 'riyazi_urdu'],
    maths: [...Array(14).keys()],
    maths_pdf_key: 'jemh1',
    ganit: [...Array(14).keys()],
    ganit_pdf_key: 'jhmh1',
    riyazi_urdu: [...Array(15).keys()],
    riyazi_urdu_pdf_key: 'jumh1',
    social_science: [
      'contemporary_india',
      'samkalin_bharat_hindi',
      'aasri_hindustan_II_urdu',
      'understanding_economic_development',
      'arthik_vikas_ki_samajh_hindi',
      'maashi_taraqqui_ki_samajh_urdu',
      'india_and_contemporary_world_II',
      'bharat_aur_samkalin_vishwa_II_hindi',
      'hindustan_aur_asri_dunia_II_urdu',
      'democratic_politics',
      'loktantrik_rajniti_hindi',
      'jamhuri_siyasat_II_urdu',
    ],
    arthik_vikas_ki_samajh_hindi: [...Array(5).keys()],
    arthik_vikas_ki_samajh_hindi_pdf_key: 'jhss2',
    maashi_taraqqui_ki_samajh_urdu: [...Array(5).keys()],
    maashi_taraqqui_ki_samajh_urdu_pdf_key: 'juss2',
    contemporary_india: [...Array(7).keys()],
    contemporary_india_pdf_key: 'jess1',
    samkalin_bharat_hindi: [...Array(7).keys()],
    samkalin_bharat_hindi_pdf_key: 'jhss1',
    understanding_economic_development: [...Array(5).keys()],
    understanding_economic_development_pdf_key: 'jess2',
    democratic_politics: [...Array(5).keys()],
    democratic_politics_pdf_key: 'jess4',
    india_and_contemporary_world_II: [...Array(5).keys()],
    india_and_contemporary_world_II_pdf_key: 'jess3',
    bharat_aur_samkalin_vishwa_II_hindi: [...Array(5).keys()],
    bharat_aur_samkalin_vishwa_II_hindi_pdf_key: 'jhss3',
    loktantrik_rajniti_hindi: [...Array(5).keys()],
    loktantrik_rajniti_hindi_pdf_key: 'jhss4',
    hindustan_aur_asri_dunia_II_urdu: [...Array(5).keys()],
    hindustan_aur_asri_dunia_II_urdu_pdf_key: 'juss3',
    aasri_hindustan_II_urdu: [...Array(7).keys()],
    aasri_hindustan_II_urdu_pdf_key: 'juss1',
    jamhuri_siyasat_II_urdu: [...Array(8).keys()],
    jamhuri_siyasat_II_urdu_pdf_key: 'juss4',
    sanskrit: ['shemushi', 'vyakaranavithi', 'abhyaswaan_bhav'],
    shemushi: [...Array(10).keys()],
    shemushi_pdf_key: 'jhsh1',
    vyakaranavithi: [...Array(14).keys()],
    vyakaranavithi_pdf_key: 'jhva1',
    abhyaswaan_bhav: [...Array(12).keys()],
    abhyaswaan_bhav_pdf_key: 'jsab1',
    science: ['vigyan_hindi', 'science_X', 'science_urdu'],
    vigyan_hindi: [...Array(13).keys()],
    vigyan_hindi_pdf_key: 'jhsc1',
    science_X: [...Array(13).keys()],
    science_X_pdf_key: 'jesc1',
    science_urdu: [...Array(16).keys()],
    science_urdu_pdf_key: 'jusc1',
    urdu: [
      'gulzar_e_urdu',
      'nawa_e_urdu',
      'door_pass',
      'jaan_pahechan',
      'sab_rang',
    ],
    jaan_pahechan: [...Array(22).keys()],
    jaan_pahechan_pdf_key: 'jujp1',
    gulzar_e_urdu: [...Array(12).keys()],
    gulzar_e_urdu_pdf_key: 'juge1',
    door_pass: [...Array(19).keys()],
    door_pass_pdf_key: 'judp1',
    nawa_e_urdu: [...Array(23).keys()],
    nawa_e_urdu_pdf_key: 'june1',
    sab_rang: [...Array(9).keys()],
    sab_rang_pdf_key: 'jusr1',
    health_and_physical_education: ['health_and_physical_education_X'],
    health_and_physical_education_X: [...Array(13).keys()],
    health_and_physical_education_X_pdf_key: 'jehp1',
  },
  {
    class: 11,
    subjects: [
      'sanskrit',
      'accountancy',
      'chemistry',
      'mathematics',
      'biology',
      'psychology',
      'geography',
      'physics',
      'hindi',
      'sociology',
      'english',
      'political_science',
      'history',
      'economics',
      'business_studies',
      'urdu',
      'home_science',
      'creative_writing_and_translation',
      'fine_art',
      'informatics_practices',
      'computer_science',
      'health_and_physical_education',
      'biotechnology',
      'sangeet',
      'knowledge_traditions_practices_of_india',
    ],
    sanskrit: ['bhaswati', 'shashwati'],
    bhaswati: [...Array(11).keys()],
    bhaswati_pdf_key: 'khsk1',
    shashwati: [...Array(11).keys()],
    shashwati_pdf_key: 'khsk2',
    accountancy: [
      'financial_accounting_I',
      'lekhashastra_I_hindi',
      'accountancy_II',
      'lekhashastra_II_hindi',
      'khatadari_I_urdu',
      'khatadari_II_urdu',
    ],
    financial_accounting_I: [...Array(7).keys()],
    financial_accounting_I_pdf_key: 'keac1',
    lekhashastra_I_hindi: [...Array(7).keys()],
    lekhashastra_I_hindi_pdf_key: 'khac1',
    accountancy_II: [...Array(2).keys()],
    accountancy_II_pdf_key: 'keac2',
    lekhashastra_II_hindi: [...Array(2).keys()],
    lekhashastra_II_hindi_pdf_key: 'khac2',
    khatadari_I_urdu: [...Array(8).keys()],
    khatadari_I_urdu_pdf_key: 'kuac1',
    khatadari_II_urdu: [...Array(5).keys()],
    khatadari_II_urdu_pdf_key: 'kuac2',
    chemistry: [
      'chemistry_part_I',
      'chemistry_part_II',
      'rasayan_vigyan_bhag_I_hindi',
      'rasayan_vigyan_bhag_II_hindi',
      'keemiya_I_urdu',
      'keemiya_II_urdu',
    ],
    chemistry_part_I: [...Array(6).keys()],
    chemistry_part_I_pdf_key: 'kech1',
    rasayan_vigyan_bhag_I_hindi: [...Array(6).keys()],
    rasayan_vigyan_bhag_I_hindi_pdf_key: 'khch1',
    keemiya_I_urdu: [...Array(7).keys()],
    keemiya_I_urdu_pdf_key: 'kuch1',
    chemistry_part_II: [...Array(3).keys()],
    chemistry_part_II_pdf_key: 'kech2',
    rasayan_vigyan_bhag_II_hindi: [...Array(3).keys()],
    rasayan_vigyan_bhag_II_hindi_pdf_key: 'khch2',
    keemiya_II_urdu: [...Array(7).keys()],
    keemiya_II_urdu_pdf_key: 'kuch2',
    mathematics: ['maths', 'ganit_hindi', 'riyazi_urdu'],
    maths: [...Array(14).keys()],
    maths_pdf_key: 'kemh1',
    ganit_hindi: [...Array(14).keys()],
    ganit_hindi_pdf_key: 'khmh1',
    riyazi_urdu: [...Array(16).keys()],
    riyazi_urdu_pdf_key: 'kumh1',
    biology: ['biology_XI', 'jeev_vigyan_hindi', 'hayatiyaat_urdu'],
    biology_XI: [...Array(19).keys()],
    biology_XI_pdf_key: 'kebo1',
    jeev_vigyan_hindi: [...Array(19).keys()],
    jeev_vigyan_hindi_pdf_key: 'khbo1',
    hayatiyaat_urdu: [...Array(22).keys()],
    hayatiyaat_urdu_pdf_key: 'kubo1',
    psychology: [
      'introduction_to_psychology',
      'manovigyan_hindi',
      'nafsiyaat_urdu',
    ],
    introduction_to_psychology: [...Array(8).keys()],
    introduction_to_psychology_pdf_key: 'kepy1',
    manovigyan_hindi: [...Array(8).keys()],
    manovigyan_hindi_pdf_key: 'khpy1',
    nafsiyaat_urdu: [...Array(9).keys()],
    nafsiyaat_urdu_pdf_key: 'kupy1',
    geography: [
      'fundamental_of_physical_geography',
      'bhautique_bhugol_ke_mool_sidhant_hindi',
      'hindustan_tabii_mahaul_urdu',
      'pratical_work_in_geography',
      'bhugol_main_prayogatmak_karya_hindi',
      'india_physical_environment',
      'bhart_bhautik_paryabaran_hindi',
      'jughrafia_mein_aamli_kam_urdu',
      'tabii_jughraiya_ka_mubadiyat_urdu',
    ],
    fundamental_of_physical_geography: [...Array(14).keys()],
    fundamental_of_physical_geography_pdf_key: 'kegy2',
    bhautique_bhugol_ke_mool_sidhant_hindi: [...Array(14).keys()],
    bhautique_bhugol_ke_mool_sidhant_hindi_pdf_key: 'khgy2',
    hindustan_tabii_mahaul_urdu: [...Array(7).keys()],
    hindustan_tabii_mahaul_urdu_pdf_key: 'kugy1',
    pratical_work_in_geography: [...Array(6).keys()],
    pratical_work_in_geography_pdf_key: 'kegy3',
    bhugol_main_prayogatmak_karya_hindi: [...Array(6).keys()],
    bhugol_main_prayogatmak_karya_hindi_pdf_key: 'khgy3',
    india_physical_environment: [...Array(6).keys()],
    india_physical_environment_pdf_key: 'kegy1',
    bhart_bhautik_paryabaran_hindi: [...Array(6).keys()],
    bhart_bhautik_paryabaran_hindi_pdf_key: 'khgy1',
    jughrafia_mein_aamli_kam_urdu: [...Array(8).keys()],
    jughrafia_mein_aamli_kam_urdu_pdf_key: 'kugy3',
    tabii_jughraiya_ka_mubadiyat_urdu: [...Array(16).keys()],
    tabii_jughraiya_ka_mubadiyat_urdu_pdf_key: 'kugm1',
    physics: [
      'physics_part_I',
      'bhautiki_I_hindi',
      'tabiyaat_I_urdu',
      'physics_part_II',
      'bhautiki_II_hindi',
      'tabiyaat_II_urdu',
    ],
    physics_part_I: [...Array(7).keys()],
    physics_part_I_pdf_key: 'keph1',
    bhautiki_I_hindi: [...Array(7).keys()],
    bhautiki_I_hindi_pdf_key: 'khph1',
    tabiyaat_I_urdu: [...Array(8).keys()],
    tabiyaat_I_urdu_pdf_key: 'kuph1',
    physics_part_II: [...Array(7).keys()],
    physics_part_II_pdf_key: 'keph2',
    bhautiki_II_hindi: [...Array(7).keys()],
    bhautiki_II_hindi_pdf_key: 'khph2',
    tabiyaat_II_urdu: [...Array(7).keys()],
    tabiyaat_II_urdu_pdf_key: 'kuph2',
    hindi: ['antra', 'aroh', 'vitan', 'antral'],
    antra: [...Array(16).keys()],
    antra_pdf_key: 'khat1',
    aroh: [...Array(16).keys()],
    aroh_pdf_key: 'khar1',
    vitan: [...Array(4).keys()],
    vitan_pdf_key: 'khvt1',
    antral: [...Array(2).keys()],
    antral_pdf_key: 'khan1',
    sociology: [
      'introducing_sociology',
      'samaj_shastra_parichay_I_hindi',
      'samajiyaat_ka_tarf_urdu',
      'understanding_society',
      'samaj_ka_bodh_hindi',
      'mutala_e_muashira_urdu',
    ],
    introducing_sociology: [...Array(5).keys()],
    introducing_sociology_pdf_key: 'kesy1',
    samaj_shastra_parichay_I_hindi: [...Array(5).keys()],
    samaj_shastra_parichay_I_hindi_pdf_key: 'khsy1',
    samajiyaat_ka_tarf_urdu: [...Array(5).keys()],
    samajiyaat_ka_tarf_urdu_pdf_key: 'kusy1',
    understanding_society: [...Array(5).keys()],
    understanding_society_pdf_key: 'kesy2',
    samaj_ka_bodh_hindi: [...Array(5).keys()],
    samaj_ka_bodh_hindi_pdf_key: 'khsy2',
    mutala_e_muashira_urdu: [...Array(5).keys()],
    mutala_e_muashira_urdu_pdf_key: 'kusy2',
    english: ['woven_words', 'hornbill', 'snapshots_suppl_reader_english'],
    woven_words: [...Array(27).keys()],
    woven_words_pdf_key: 'keww1',
    hornbill: [...Array(14).keys()],
    hornbill_pdf_key: 'kehb1',
    snapshots_suppl_reader_english: [...Array(6).keys()],
    snapshots_suppl_reader_english_pdf_key: 'kesp1',
    political_science: [
      'political_theory',
      'raajneeti_sidhant_hindi',
      'siyasi_nazaria_urdu',
      'india_constitution_at_work',
      'bharat_ka_samvidhan_sidhant_aur_vyavhar_hindi',
      'hindustani_aain_aur_kaam_urdu',
    ],
    political_theory: [...Array(8).keys()],
    political_theory_pdf_key: 'keps1',
    raajneeti_sidhant_hindi: [...Array(8).keys()],
    raajneeti_sidhant_hindi_pdf_key: 'khps1',
    hindustani_aain_aur_kaam_urdu: [...Array(10).keys()],
    hindustani_aain_aur_kaam_urdu_pdf_key: 'kups1',
    india_constitution_at_work: [...Array(10).keys()],
    india_constitution_at_work_pdf_key: 'keps2',
    bharat_ka_samvidhan_sidhant_aur_vyavhar_hindi: [...Array(10).keys()],
    bharat_ka_samvidhan_sidhant_aur_vyavhar_hindi_pdf_key: 'khps2',
    siyasi_nazaria_urdu: [...Array(10).keys()],
    siyasi_nazaria_urdu_pdf_key: 'kups2',
    history: [
      'themes_in_world_history',
      'vishwa_itihas_ke_kuch_vishay_hindi',
      'tareekh_e_alam_per_mabni_mauzuaat_part_I_urdu',
    ],
    themes_in_world_history: [...Array(7).keys()],
    themes_in_world_history_pdf_key: 'kehs1',
    vishwa_itihas_ke_kuch_vishay_hindi: [...Array(7).keys()],
    vishwa_itihas_ke_kuch_vishay_hindi_pdf_key: 'khhs1',
    tareekh_e_alam_per_mabni_mauzuaat_part_I_urdu: [...Array(11).keys()],
    tareekh_e_alam_per_mabni_mauzuaat_part_I_urdu_pdf_key: 'kuta1',
    economics: [
      'indian_economic_development',
      'statistics_for_economics',
      'bhartiya_airthryavstha_ka_vikas_hindi',
      'sankhyiki_hindi',
      'hindustan_ki_moaashi_tarraqqi_urdu',
      'shumariyaat_bar_e_mushiyat_urdu',
    ],
    indian_economic_development: [...Array(8).keys()],
    indian_economic_development_pdf_key: 'keec1',
    statistics_for_economics: [...Array(8).keys()],
    statistics_for_economics_pdf_key: 'kest1',
    sankhyiki_hindi: [...Array(8).keys()],
    sankhyiki_hindi_pdf_key: 'khst1',
    bhartiya_airthryavstha_ka_vikas_hindi: [...Array(8).keys()],
    bhartiya_airthryavstha_ka_vikas_hindi_pdf_key: 'khec1',
    hindustan_ki_moaashi_tarraqqi_urdu: [...Array(10).keys()],
    hindustan_ki_moaashi_tarraqqi_urdu_pdf_key: 'kuec1',
    shumariyaat_bar_e_mushiyat_urdu: [...Array(9).keys()],
    shumariyaat_bar_e_mushiyat_urdu_pdf_key: 'kusc1',
    business_studies: [
      'business_studies_XI',
      'vyavsay_adhyanan_hindi',
      'karobari_mutalah_I_urdu',
    ],
    business_studies_XI: [...Array(11).keys()],
    business_studies_XI_pdf_keys: 'kebs1',
    vyavsay_adhyanan_hindi: [...Array(11).keys()],
    vyavsay_adhyanan_hindi_pdf_key: 'khbs1',
    karobari_mutalah_I_urdu: [...Array(11).keys()],
    karobari_mutalah_I_urdu_pdf_key: 'kubs1',
    urdu: ['nai_awaz', 'dhanak', 'gulistan_e_adab', 'khyabane_urdu'],
    nai_awaz: [...Array(20).keys()],
    nai_awaz_pdf_key: 'kuna1',
    dhanak: [...Array(27).keys()],
    dhanak_pdf_key: 'kudh1',
    gulistan_e_adab: [...Array(22).keys()],
    gulistan_e_adab_pdf_key: 'kuga1',
    khyabane_urdu: [...Array(15).keys()],
    khyabane_urdu_pdf_key: 'kuku1',
    home_science: [
      'human_ecology_and_family_sciences_part_I',
      'human_ecology_and_family_sciences_part_II',
      'manav_paristhitiki_evm_pariwar_vigyan_bhag_I_hindi',
      'manav_paristhitiki_evm_pariwar_vigyan_bhag_II_hindi',
      'insani_mahauliyat_aur_uloom_e_khandandari_I_urdu',
      'insani_mahauliyat_aur_uloom_e_khandandari_II_urdu',
    ],
    human_ecology_and_family_sciences_part_I: [...Array(7).keys()],
    human_ecology_and_family_sciences_part_I_pdf_key: 'kehe1',
    human_ecology_and_family_sciences_part_II: [...Array(4).keys()],
    human_ecology_and_family_sciences_part_II_pdf_key: 'kehe2',
    manav_paristhitiki_evm_pariwar_vigyan_bhag_I_hindi: [...Array(7).keys()],
    manav_paristhitiki_evm_pariwar_vigyan_bhag_I_hindi_pdf_key: 'khhe1',
    manav_paristhitiki_evm_pariwar_vigyan_bhag_II_hindi: [...Array(5).keys()],
    manav_paristhitiki_evm_pariwar_vigyan_bhag_II_hindi_pdf_key: 'khhe2',
    insani_mahauliyat_aur_uloom_e_khandandari_I_urdu: [...Array(10).keys()],
    insani_mahauliyat_aur_uloom_e_khandandari_I_urdu_pdf_key: 'kuim1',
    insani_mahauliyat_aur_uloom_e_khandandari_II_urdu: [...Array(9).keys()],
    insani_mahauliyat_aur_uloom_e_khandandari_II_urdu_pdf_key: 'kuim2',
    creative_writing_and_translation: ['srijan', 'takhleequi_jauhar'],
    srijan: [...Array(4).keys()],
    srijan_pdf_key: 'khsr1',
    takhleequi_jauhar: [...Array(4).keys()],
    takhleequi_jauhar_pdf_key: 'kucw1',
    fine_art: [
      'an_introduction_to_indian_art_part_I',
      'bhartiya_kala_ka_parichay',
    ],
    an_introduction_to_indian_art_part_I: [...Array(8).keys()],
    an_introduction_to_indian_art_part_I_pdf_key: 'kefa1',
    bhartiya_kala_ka_parichay: [...Array(8).keys()],
    bhartiya_kala_ka_parichay_pdf_key: 'khfa1',
    informatics_practices: ['informatics_practices_XI'],
    informatics_practices_XI: [...Array(8).keys()],
    informatics_practices_XI_pdf_key: 'keip1',
    computer_science: ['computer_science_XI'],
    computer_science_XI: [...Array(11).keys()],
    computer_science_XI_pdf_key: 'kecs1',
    health_and_physical_education: ['health_and_physical_education_XI'],
    health_and_physical_education_XI: [...Array(11).keys()],
    health_and_physical_education_XI_pdf_key: 'kehp1',
    biotechnology: ['biotechnology_XI'],
    biotechnology_XI: [...Array(12).keys()],
    biotechnology_XI_pdf_key: 'kebt1',
    sangeet: ['tabla_evam_pakhawaj', 'hindustani_sangeet_gayan_evam_vadan'],
    tabla_evam_pakhawaj: [...Array(8).keys()],
    tabla_evam_pakhawaj_pdf_key: 'khtp1',
    hindustani_sangeet_gayan_evam_vadan: [...Array(10).keys()],
    hindustani_sangeet_gayan_evam_vadan_pdf_key: 'khgv1',
    knowledge_traditions_practices_of_india: [
      'knowledge_traditions_practices_of_india_XI',
    ],
    knowledge_traditions_practices_of_india_XI: [...Array(9).keys()],
    knowledge_traditions_practices_of_india_XI_pdf_key: 'keks1',
  },
  {
    class: 12,
    subjects: [
      'mathematics',
      'physics',
      'accountancy',
      'sanskrit',
      'hindi',
      'english',
      'biology',
      'history',
      'geography',
      'psychology',
      'sociology',
      'chemistry',
      'political_science',
      'economics',
      'business_studies',
      'home_science',
      'urdu',
      'creative_writing_and_translation',
      'fine_art',
      'computer_science',
      'informatics_practices',
    ],
    mathematics: [
      'mathematics_part_I',
      'mathematics_part_II',
      'ganit_I_hindi',
      'ganit_II_hindi',
      'riyazi_I_urdu',
      'riyazi_II_urdu',
    ],
    mathematics_part_I: [...Array(6).keys()],
    mathematics_part_I_pdf_key: 'lemh1',
    mathematics_part_II: [...Array(7).keys()],
    mathematics_part_II_pdf_key: 'lemh2',
    ganit_I_hindi: [...Array(6).keys()],
    ganit_I_hindi_pdf_key: 'lhmh1',
    ganit_II_hindi: [...Array(7).keys()],
    ganit_II_hindi_pdf_key: 'lhmh2',
    riyazi_I_urdu: [...Array(6).keys()],
    riyazi_I_urdu_pdf_key: 'lumh1',
    riyazi_II_urdu: [...Array(7).keys()],
    riyazi_II_urdu_pdf_key: 'lumh2',
    physics: [
      'physics_part_I',
      'physics_part_II',
      'bhautiki_I_hindi',
      'bhautiki_II_hindi',
      'tabiyaat_I_urdu',
      'tabiyaat_II_urdu',
    ],
    physics_part_I: [...Array(8).keys()],
    physics_part_I_pdf_key: 'leph1',
    physics_part_II: [...Array(6).keys()],
    physics_part_II_pdf_key: 'leph2',
    bhautiki_I_hindi: [...Array(8).keys()],
    bhautiki_I_hindi_pdf_key: 'lhph1',
    bhautiki_II_hindi: [...Array(6).keys()],
    bhautiki_II_hindi_pdf_key: 'lhph2',
    tabiyaat_I_urdu: [...Array(8).keys()],
    tabiyaat_I_urdu_pdf_key: 'luph1',
    tabiyaat_II_urdu: [...Array(6).keys()],
    tabiyaat_II_urdu_pdf_key: 'luph2',
    accountancy: [
      'accountancy_I',
      'accountancy_part_II',
      'lekhashastra_part_I_hindi',
      'lekhashastra_part_II_hindi',
      'computerised_accounting_system',
      'khatadari_I_urdu',
      'khatadari_II_urdu',
    ],
    accountancy_I: [...Array(4).keys()],
    accountancy_I_pdf_key: 'leac1',
    accountancy_part_II: [...Array(6).keys()],
    accountancy_part_II_pdf_key: 'leac2',
    lekhashastra_part_I_hindi: [...Array(4).keys()],
    lekhashastra_part_I_hindi_pdf_key: 'lhac1',
    lekhashastra_part_II_hindi: [...Array(5).keys()],
    lekhashastra_part_II_hindi_pdf_key: 'lhac2',
    computerised_accounting_system: [...Array(4).keys()],
    computerised_accounting_system_pdf_key: 'leca1',
    khatadari_I_urdu: [...Array(5).keys()],
    khatadari_I_urdu_pdf_key: 'luac1',
    khatadari_II_urdu: [...Array(6).keys()],
    khatadari_II_urdu_pdf_key: 'luac2',
    sanskrit: ['bhaswati', 'shaswati'],
    bhaswati: [...Array(10).keys()],
    bhaswati_pdf_key: 'lhsk1',
    shaswati: [...Array(11).keys()],
    shaswati_pdf_key: 'lhsk2',
    hindi: ['antra', 'aroh', 'vitan', 'antral_bhag_2'],
    antra: [...Array(21).keys()],
    antra_pdf_key: 'lhat1',
    aroh: [...Array(15).keys()],
    aroh_pdf_key: 'lhar1',
    vitan: [...Array(3).keys()],
    vitan_pdf_key: 'lhvt1',
    antral_bhag_2: [...Array(3).keys()],
    antral_bhag_2_pdf_key: 'lhan1',
    english: ['kaliedoscope', 'flamingo', 'vistas'],
    kaliedoscope: [...Array(21).keys()],
    kaliedoscope_pdf_key: 'lekl1',
    flamingo: [...Array(13).keys()],
    flamingo_pdf_key: 'lefl1',
    vistas: [...Array(6).keys()],
    vistas_pdf_key: 'levt1',
    biology: ['biology_XII', 'jeev_vigyan', 'hayatiyaat'],
    biology_XII: [...Array(13).keys()],
    biology_XII_pdf_key: 'lebo1',
    jeev_vigyan: [...Array(13).keys()],
    jeev_vigyan_pdf_key: 'lhbo1',
    hayatiyaat: [...Array(16).keys()],
    hayatiyaat_pdf_key: 'lubo1',
    history: [
      'themes_in_indian_history_I',
      'themes_in_indian_history_II',
      'themes_in_indian_history_III',
      'bharatiya_itihas_ke_kuchh_vishay_I_hindi',
      'bharatiya_itihas_ke_kuchh_vishay_II_hindi',
      'bharatiya_itihas_ke_kuchh_vishay_III_hindi',
      'tareekh_e_hind_ke_mauzuaat_I_urdu',
      'tareekh_e_hind_ke_mauzuaat_II_urdu',
      'tareekh_e_hind_ke_mauzuaat_III_urdu',
    ],
    themes_in_indian_history_I: [...Array(4).keys()],
    themes_in_indian_history_I_pdf_key: 'lehs1',
    bharatiya_itihas_ke_kuchh_vishay_I_hindi: [...Array(4).keys()],
    bharatiya_itihas_ke_kuchh_vishay_I_hindi_pdf_key: 'lhhs1',
    themes_in_indian_history_II: [...Array(4).keys()],
    themes_in_indian_history_II_pdf_key: 'lehs2',
    bharatiya_itihas_ke_kuchh_vishay_II_hindi: [...Array(4).keys()],
    bharatiya_itihas_ke_kuchh_vishay_II_hindi_pdf_key: 'lhhs2',
    themes_in_indian_history_III: [...Array(4).keys()],
    themes_in_indian_history_III_pdf_key: 'lehs3',
    bharatiya_itihas_ke_kuchh_vishay_III_hindi: [...Array(4).keys()],
    bharatiya_itihas_ke_kuchh_vishay_III_hindi_pdf_key: 'lhhs3',
    tareekh_e_hind_ke_mauzuaat_I_urdu: [...Array(4).keys()],
    tareekh_e_hind_ke_mauzuaat_I_urdu_pdf_key: 'luth1',
    tareekh_e_hind_ke_mauzuaat_II_urdu: [...Array(5).keys()],
    tareekh_e_hind_ke_mauzuaat_II_urdu_pdf_key: 'luth2',
    tareekh_e_hind_ke_mauzuaat_III_urdu: [...Array(6).keys()],
    tareekh_e_hind_ke_mauzuaat_III_urdu_pdf_key: 'luth3',
    geography: [
      'fundamentals_of_human_geography',
      'practical_work_in_geography_part_II',
      'manav_bhugol_ke_mool_sidhant_hindi',
      'bhugol_main_peryojnatmak_pryogatmak_karye_hindi',
      'india_people_and_economy',
      'bharat_log_aur_arthvyasastha_hindi',
      'insani_jughrafia_ke_buniyadi_usool_urdu',
      'hindustan_awam_aur_maishat_urdu',
      'jughrafia_mein_aamli_kam_urdu',
    ],
    fundamentals_of_human_geography: [...Array(8).keys()],
    fundamentals_of_human_geography_pdf_key: 'legy1',
    practical_work_in_geography_part_II: [...Array(6).keys()],
    practical_work_in_geography_part_II_pdf_key: 'legy3',
    manav_bhugol_ke_mool_sidhant_hindi: [...Array(8).keys()],
    manav_bhugol_ke_mool_sidhant_hindi_pdf_key: 'lhgy1',
    bhugol_main_peryojnatmak_pryogatmak_karye_hindi: [...Array(4).keys()],
    bhugol_main_peryojnatmak_pryogatmak_karye_hindi_pdf_key: 'lhgy3',
    india_people_and_economy: [...Array(9).keys()],
    india_people_and_economy_pdf_key: 'legy2',
    bharat_log_aur_arthvyasastha_hindi: [...Array(9).keys()],
    bharat_log_aur_arthvyasastha_hindi_pdf_key: 'lhgy2',
    insani_jughrafia_ke_buniyadi_usool_urdu: [...Array(10).keys()],
    insani_jughrafia_ke_buniyadi_usool_urdu_pdf_key: 'lufh1',
    hindustan_awam_aur_maishat_urdu: [...Array(12).keys()],
    hindustan_awam_aur_maishat_urdu_pdf_key: 'lugy1',
    jughrafia_mein_aamli_kam_urdu: [...Array(6).keys()],
    jughrafia_mein_aamli_kam_urdu_pdf_key: 'lugy3',
    psychology: ['psychology_XII', 'manovigyan_hindi', 'nafsiat_urdu'],
    psychology_XII: [...Array(7).keys()],
    psychology_XII_pdf_key: 'lepy1',
    manovigyan_hindi: [...Array(7).keys()],
    manovigyan_hindi_pdf_key: 'lhpy1',
    nafsiat_urdu: [...Array(9).keys()],
    nafsiat_urdu_pdf_key: 'lupy1',
    sociology: [
      'indian_society',
      'bhartiya_samaj_hindi',
      'social_change_and_development_in_india',
      'bharat_main_samajik_parivartan_aur_vikas_hindi',
      'hindustani_samaj_urdu',
      'hindustan_mein_samaji_tabdili_aur_taraqqi_urdu',
    ],
    indian_society: [...Array(7).keys()],
    indian_society_pdf_key: 'lesy1',
    bhartiya_samaj_hindi: [...Array(7).keys()],
    bhartiya_samaj_hindi_pdf_key: 'lhsy1',
    social_change_and_development_in_india: [...Array(8).keys()],
    social_change_and_development_in_india_pdf_key: 'lesy2',
    bharat_main_samajik_parivartan_aur_vikas_hindi: [...Array(8).keys()],
    bharat_main_samajik_parivartan_aur_vikas_hindi_pdf_key: 'lhsy2',
    hindustani_samaj_urdu: [...Array(7).keys()],
    hindustani_samaj_urdu_pdf_key: 'luis1',
    hindustan_mein_samaji_tabdili_aur_taraqqi_urdu: [...Array(8).keys()],
    hindustan_mein_samaji_tabdili_aur_taraqqi_urdu_pdf_key: 'lusy2',
    chemistry: [
      'chemistry_I',
      'chemistry_II',
      'rasayan_vigyan_bhag_I_hindi',
      'rasayan_vigyan_bhag_II_hindi',
      'keemiya_I',
      'keemiya_II',
    ],
    chemistry_I: [...Array(5).keys()],
    chemistry_I_pdf_key: 'lech1',
    chemistry_II: [...Array(5).keys()],
    chemistry_II_pdf_key: 'lech2',
    rasayan_vigyan_bhag_I_hindi: [...Array(5).keys()],
    rasayan_vigyan_bhag_I_hindi_pdf_key: 'lhch1',
    rasayan_vigyan_bhag_II_hindi: [...Array(5).keys()],
    rasayan_vigyan_bhag_II_hindi_pdf_key: 'lhch2',
    keemiya_I: [...Array(9).keys()],
    keemiya_I_pdf_key: 'luch1',
    keemiya_II: [...Array(7).keys()],
    keemiya_II_pdf_key: 'luch2',
    political_science: [
      'contemporary_world_politics',
      'samkalin_vishwa_rajniti_hindi',
      'politics_in_india_since_independence',
      'swatantra_bharat_mein_rajniti_II_hindi',
      'aasri_alami_siyasat_urdu',
      'azadi_ke_baad_hindustan_ki_siyasat_urdu',
    ],
    contemporary_world_politics: [...Array(7).keys()],
    contemporary_world_politics_pdf_key: 'leps1',
    samkalin_vishwa_rajniti_hindi: [...Array(7).keys()],
    samkalin_vishwa_rajniti_hindi_pdf_key: 'lhps1',
    politics_in_india_since_independence: [...Array(8).keys()],
    politics_in_india_since_independence_pdf_key: 'leps2',
    swatantra_bharat_mein_rajniti_II_hindi: [...Array(8).keys()],
    swatantra_bharat_mein_rajniti_II_hindi_pdf_key: 'lhps2',
    aasri_alami_siyasat_urdu: [...Array(9).keys()],
    aasri_alami_siyasat_urdu_pdf_key: 'lups1',
    azadi_ke_baad_hindustan_ki_siyasat_urdu: [...Array(9).keys()],
    azadi_ke_baad_hindustan_ki_siyasat_urdu_pdf_key: 'luab1',
    economics: [
      'introductory_microeconomics',
      'introductory_macroeconomics',
      'vyashthi_arthshasrta_hindi',
      'samashty_arthshastra_ek_parichay_hindi',
      'juzvi_maashiyat_ka_taruf_urdu',
      'kulli_maashiyat_ka_taruf_urdu',
    ],
    introductory_microeconomics: [...Array(5).keys()],
    introductory_microeconomics_pdf_key: 'leec2',
    introductory_macroeconomics: [...Array(6).keys()],
    introductory_macroeconomics_pdf_key: 'leec1',
    vyashthi_arthshasrta_hindi: [...Array(5).keys()],
    vyashthi_arthshasrta_hindi_pdf_key: 'lhec2',
    samashty_arthshastra_ek_parichay_hindi: [...Array(6).keys()],
    samashty_arthshastra_ek_parichay_hindi_pdf_key: 'lhec1',
    juzvi_maashiyat_ka_taruf_urdu: [...Array(6).keys()],
    juzvi_maashiyat_ka_taruf_urdu_pdf_key: 'lume1',
    kulli_maashiyat_ka_taruf_urdu: [...Array(6).keys()],
    kulli_maashiyat_ka_taruf_urdu_pdf_key: 'lume2',
    business_studies: [
      'business_studies_I',
      'vyavasai_adhyan_I_hindi',
      'business_studies_II',
      'vyavasai_adhyan_II_hindi',
      'karobari_uloom_I_urdu',
      'karobari_uloom_II_urdu',
    ],
    business_studies_I: [...Array(8).keys()],
    business_studies_I_pdf_key: 'lebs1',
    vyavasai_adhyan_I_hindi: [...Array(8).keys()],
    vyavasai_adhyan_I_hindi_pdf_key: 'lhbs1',
    business_studies_II: [...Array(3).keys()],
    business_studies_II_pdf_key: 'lebs2',
    vyavasai_adhyan_II_hindi: [...Array(3).keys()],
    vyavasai_adhyan_II_hindi_pdf_key: 'lhbs2',
    karobari_uloom_I_urdu: [...Array(8).keys()],
    karobari_uloom_I_urdu_pdf_key: 'lubs1',
    karobari_uloom_II_urdu: [...Array(4).keys()],
    karobari_uloom_II_urdu_pdf_key: 'lubs2',
    home_science: [
      'human_ecology_and_family_sciences_part_I',
      'human_ecology_and_family_sciences_part_II',
      'manav_paristhitik_avam_parivar_vigyan_bhag_I_hindi',
      'manav_paristhitik_avam_parivar_vigyan_bhag_II_hindi',
    ],
    human_ecology_and_family_sciences_part_I: [...Array(7).keys()],
    human_ecology_and_family_sciences_part_I_pdf_key: 'lehe1',
    human_ecology_and_family_sciences_part_II: [...Array(7).keys()],
    human_ecology_and_family_sciences_part_II_pdf_key: 'lehe2',
    manav_paristhitik_avam_parivar_vigyan_bhag_I_hindi: [...Array(7).keys()],
    manav_paristhitik_avam_parivar_vigyan_bhag_I_hindi_pdf_key: 'lehh1',
    manav_paristhitik_avam_parivar_vigyan_bhag_II_hindi: [...Array(7).keys()],
    manav_paristhitik_avam_parivar_vigyan_bhag_II_hindi_pdf_key: 'lehh2',
    urdu: ['gulistan_e_adab', 'khayaban_e_urdu', 'nai_awaz', 'dhanak'],
    gulistan_e_adab: [...Array(12).keys()],
    gulistan_e_adab_pdf_key: 'luga1',
    khayaban_e_urdu: [...Array(6).keys()],
    khayaban_e_urdu_pdf_key: 'luku1',
    nai_awaz: [...Array(16).keys()],
    nai_awaz_pdf_key: 'luna1',
    dhanak: [...Array(12).keys()],
    dhanak_pdf_key: 'ludh1',
    creative_writing_and_translation: ['srijan_II', 'takhleequi_jauhar'],
    srijan_II: [...Array(4).keys()],
    srijan_II_pdf_key: 'khsr2',
    takhleequi_jauhar: [...Array(11).keys()],
    takhleequi_jauhar_pdf_key: 'lucw1',
    fine_art: [
      'an_introduction_to_indian_art_part_II',
      'bhartiya_kala_ka_itihaas_bhag_2_hindi',
    ],
    an_introduction_to_indian_art_part_II: [...Array(8).keys()],
    an_introduction_to_indian_art_part_II_pdf_key: 'lefa1',
    bhartiya_kala_ka_itihaas_bhag_2_hindi: [...Array(8).keys()],
    bhartiya_kala_ka_itihaas_bhag_2_hindi_pdf_key: 'lhfa1',
    computer_science: ['computer_science_XII'],
    computer_science_XII: [...Array(13).keys()],
    computer_science_XII_pdf_key: 'lecs1',
    informatics_practices: ['informatics_practices_XII'],
    informatics_practices_XII: [...Array(7).keys()],
    informatics_practices_XII_pdf_key: 'leip1',
  },
  {
    class: '11 & 12 combined',
    subjects: ['hindi', 'sanskrit', 'urdu'],
    hindi: ['abhivyakti_aur_madhyam'],
    abhivyakti_aur_madhyam: [...Array(16).keys()],
    abhivyakti_aur_madhyam_pdf_key: 'kham1',
    sanskrit: ['sanskrit_sahitya_parichay'],
    sanskrit_sahitya_parichay: [...Array(12).keys()],
    sanskrit_sahitya_parichay_pdf_key: 'klss1',
    urdu: [
      'zuban_O_Adab_ki_tareekh',
      'urdu_qwaid_aur_insha',
      'izhar_aur_zara_e_izhar',
    ],
    zuban_O_Adab_ki_tareekh: [...Array(23).keys()],
    zuban_O_Adab_ki_tareekh_pdf_key: 'kuza1',
    urdu_qwaid_aur_insha: [...Array(24).keys()],
    urdu_qwaid_aur_insha_pdf_key: 'juuq1',
    izhar_aur_zara_e_izhar: [...Array(4).keys()],
    izhar_aur_zara_e_izhar_pdf_key: 'kuiz1',
  },
];

export const SOLUTIONS_ARRAY = [
  {
    class: 12,
    subjects: ['accountancy', 'mathematics', 'physics', 'english'],
    accountancy: ['accountancy_I', 'accountancy_part_II'],
    accountancy_I: [...Array(4).keys()],
    accountancy_I_solutions: [
      'QmeXsmzPVGtnT7cCEF1d48fPHSPfU58GCCPCxmv5ZfqBxu',
      'QmUfePkM7DjNUFA5qZdKYmLySLrUm2KJnAXRbSTFfunhcW',
      'QmQrURrrrVck76uANRupnoF7KVwN82WRTEEdUuK34tSfBi',
      'QmSMjtsCmmXusC5jVn1AeNXCxsczgijh1UpVzFuWt9f6Fw',
    ],
    accountancy_part_II: [...Array(6).keys()],
    accountancy_part_II_solutions: [
      'QmPmjrRvhwvHF5CZKGJ1wkXzmaZwQfgCQpJeAdSyix3hiK',
      'QmPfqi3UK6H3zpBZs4s6hu981S5GMg51PoeWZzMXcWUGk1',
      'QmRKefW7qyuGsUYjVV5Ce7ZPuHz5DUSTyDH2tY34eWJtbK',
      'QmQXoaGTsrBht75vjb6MwJA1rJanYhyTKZodsseMaGPnQ7',
      'QmZurGy5aakcLRJnye9YfsjYnDTodMPD5s33B5o89AcyH3',
      'QmPDwRo8rLUuDhB6AcMmNRAsN62Mtm4RrToYHDqtcyd7Em',
    ],
    mathematics: ['maths'],
    maths: [...Array(13).keys()],
    maths_solutions: [
      'QmTG5g21ErmhutNXAGunKqbQx6zDkPVSbFZYuem4yj9VXY',
      'QmWARaj5VFm4imZB1wGGbc3fn8ZHBkapJ3BpxyB3RAkQGj',
      'QmRUmUGM6sXbzZFMvVFST9EYyMw6898837tTCezgEZqvDw',
      'QmQ8ezp359UUKwYbq77dnTSpyABuTuVaCKBr4m9FowvySh',
      'QmXWtpsshzSa9tCtV2emWciHzykny9K9oWxAb21Z3CBLTG',
      'QmbRZsfnkXo6vLHmrMsE1R32AmopVp3kvFreudkCDwGY47',
      'QmYDTghsF4tRctdGyWkEiq3hat4YWjK6vJy5dpaY9bupJr',
      'QmWfMv2JLZEQ2HomE98y1zKBYZmKQT1bKWsDEkvRbaM5Nd',
      'QmTSS8cYeVVGVGCmgom2QrTNh3z2Fpg42mxoipvwSjs3an',
      'Qme3w4neMBDiWGUvpdkgKf3nikNXxtVdBJLLHcoY4eatcL',
      'QmeEe9YahgbvqLdMMnK8dzZ3ZfKRDoc8yFCZTZjpVSCJ8Q',
      'QmU7yKkoARMBVTraghj625NNyKFuy8uZELyVmzvNqgxfuf',
    ],
    physics: ['physics_XII'],
    physics_XII: [...Array(13).keys()],
    physics_XII_solutions: [
      'QmYvy86KDGPHbQiGeHNYaf2YGPtgVF8jEbPgGBVYaz9GhE',
      'QmUJuPxzHpPcL3bLTccA7fcMKm65TMMu7KUwpoVC9p6jD5',
      'QmU9RsGCUjC6UQETrfjBfzeK61p1S7HTfNeEE4e7fDgyYq',
      'QmaavEuw9r3epGodwdeQ8YWUGaxpD34uAdVjesdF9b7vZA',
      'QmT1d9iDhP7zhFy3Msg1bbpszswzg8mQjXs6x4wtCduPZ5',
      'QmUFiFUEonUStBC35EsWwmSpuzPdGSxyCryEMHo2kxhYLH',
      'QmaW9YHd6zBke4WfzCNuhtB3nR1RWK4gTEtEbfSLP8Qgwq',
      'QmRYoEnuLeWFGghDLRWC8tzpBnivTXVuPUxxx6YMY4HEs6',
      'QmXnxC6t8odVzzhP2VbUkcTcQnjkuj4hzi8xhDEYu7XE7B',
      'QmRnbjUNRpX7gWRojucofKpNtvr533a2J9GVS7CpKuVHtf',
      'QmWmyYbnjphED7U92U3buv7kek6EpSNfNQUdgWdz6RzF4y',
      'QmQYURpdEtzKEB7NhqGf3g5QYxwdwef7b53HdpwB93276X',
      'QmXgk3WoJPVsMR28XfgsDT2zK3Sqvr7UuTaqEPVeDQ2SYk',
      'QmSbXbhTedv6B8MgxXWYeysFxYbKCpfC4ddZ9EWc7BDQTy',
      'QmVoqYYFvLBsLRRHkxDQ23mVx4ctFbXTMuwnmegi98gnCC',
    ],
    english: ['vista', 'flamingo'],
    vista: [...Array(8).keys()],
    vista_solutions: [
      'QmbrpM2qX8qM4zMgMnWD7trmQ3kUerJKNUEFu6ku6h3yHR',
      'QmahyTsnQokuf9wAAf4e8eL9V7bq46G8YRD7eVjG3oZbo3',
      'QmP4hv72YsGvyVHMrGGAH5TS9Edd3ULS91fkmCMQGHY5FB',
      'QmVh7BDKJvqwgcwvZcR8UVsn7XaywUiJQQpmoAPR32jXne',
      'QmZKCZT13PWsWaThoeJAEEjtEfzhi17Yjd9Q8mqECsrBmJ',
      'Qmf24DeAjTrci7WPZ6c9pjHNV6hHqpynmfyuM59nLpCvzy',
      'QmUsdrZepHDZVZQHPVnsbju3ERn48aX9a8PGScUexhq5Wu',
      'QmXsTJ8gdoCCkHjntsCHo3QzK1TMMakCcmgX4JDSkFpgdo',
    ],
    flamingo: [...Array(11).keys()],
    flamingo_solutions: [
      'QmbhvFgakUmRCPVVYKxLxxrGhZXYnbzWcL7L822foqxWnK',
      'QmVCLdpQnTC2PFSaawQh93HUMjXS7DTJXi5D31ktcZ6e3Q',
      'QmfHBu425HS8fyPTBUwL11X6jsH92hqxmEjYixaJU3knB4',
      'QmPMZYE5Mxc3Z6LM5L3ij7PFdzjomsQ6NYEgaho52K7inV',
      'Qme9tfcCxMDEdpT3yuexAHGkMf6KoctQABstANSnYvVh8Z',
      'QmQEhhzp9NnyzSwyBqXhbQ2RxQHrQjaTcWKgGk5opbWKaE',
      'QmUhhX4YVB2GfG9ErEWQmuuaBaATcoHHfoVH6ZNcTsei73',
      'QmRZ1MpvQc8Vb3Lfezuccauh6ftpkheQFPwhBLz3S82KQy',
      'QmP3Y2Jpyb2oGWTnbtE8FVwowEvDfd28fywtnx2cEYenJg',
      'QmaC1oSvNB7eF6VrVJkGik63J1gQtNyY9ooKfmitmFjdio',
      'QmdPmRWSousULPUcFSqjKa2tT3DLGWu674U2TvqvERLwTg',
    ],
  },
];
